# Generated by Django 3.0.5 on 2023-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20230428_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='others', max_length=40),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
